/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 */
public class FluxScopeProvider extends AbstractDeclarativeScopeProvider {
	// see http://www.eclipse.org/Xtext/documentation.html#scoping
}
