/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FluxUiModule extends org.culturegraph.mf.ide.ui.AbstractFluxUiModule {
	public FluxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
