/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MetatextUiModule extends org.culturegraph.mf.ide.ui.AbstractMetatextUiModule {
	public MetatextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
