/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide.ui.contentassist;

import org.culturegraph.mf.ide.ui.contentassist.AbstractFluxProposalProvider;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class FluxProposalProvider extends AbstractFluxProposalProvider {

}
