/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide.ui.contentassist;

/**
 * Customize the content assistant
 */
public class FluxProposalProvider extends AbstractFluxProposalProvider {
	// see http://www.eclipse.org/Xtext/documentation.html#contentAssist
}
