/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FluxRuntimeModule extends org.culturegraph.mf.ide.AbstractFluxRuntimeModule {

}
