/*
 * generated by Xtext
 */
package org.culturegraph.mf.ide.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FluxOutlineTreeProvider extends DefaultOutlineTreeProvider {
	// see http://www.eclipse.org/Xtext/documentation.html#outline
}
